#ENC[AES256_GCM,data:ey5WJ7TqED5alcM7LQWO0zk8evN2SUVtMBw6lbhXkHALHDJkJ2UV/fAAAFk6sGCM7qtx2pkcjFovn7sH,iv:EAki0dmjZpkkSYHfQhYQ/qXefaoy98gdWOgFmElhKM0=,tag:bvKl91neWrK+dfTse7t5Gw==,type:comment]
#ENC[AES256_GCM,data:SPPfaC1VLxPSY37R5XZasLqsyEWemCzWJx0tngQITvZ10k9WYmJXxg==,iv:mYLyQDOEkXaGpBhCmq+eD/Z0PAQOwPxeZ//IZ1/OJ+Q=,tag:ybfFRs6CIt9o7Bd9UbefMA==,type:comment]
#ENC[AES256_GCM,data:HRDMQH3s+/ECywQxPntTc0YAdC8zv38OPsR/DlyzScFFZK04kw0Wm+dY57Fe8MQ0D3OoaotGOgYU8Suf2CyiqZo=,iv:yeNVvAykOaQZG/VLpagyG4Mb3Xf6YbDm2J+KQN2L/lg=,tag:3wortZpYyzqZMhv63movAg==,type:comment]
vps_user: ENC[AES256_GCM,data:CNyo4OGm1CQ=,iv:RPoHRPo2D8V3SdF5mRfqX/gRS+H3KtNRQzN8gBWwmgg=,tag:IyIIia6jrSwSde1+NCagxA==,type:str]
#ENC[AES256_GCM,data:0mOD6S2eKloO3fMufDCvHREVXkukFA0FvpBNbgHhatl/FjYtnW6vqcenXpe0cRoCQm5Rd5/S1W28nNA=,iv:24bZ5MvuKYfYAokyORYq8d5taPtAkLsapPJLzALksqc=,tag:+riEYNVtZ+d6Aq1q2y1Ogw==,type:comment]
vps_user_pubkeys:
    - ENC[AES256_GCM,data:0yZwyQzMMYQYORh/2w+qdv1tMTvdwlZJLUBkb21MJNCX0+PJhEYTMJfOdJkGzTO857zLUDQnNWAjoFnmrYh3sdKmFofOQflkqZwF+MQgMWz+ar91cuVyYBOqCOLepgLBaPr4wfUCqI1As+hZzgx/z2KEz1YnRQZXr7SKaS67XklX5dsPovoDBvChlknZ,iv:GDMYRo3Lt8V11FO9cPqrOLz1VtrtbBWcNL0/7j/bsP0=,tag:SkZyyxQwVjKoAKZ6IkCQCw==,type:str]
    - ENC[AES256_GCM,data:wk8GTD7vZqgvGFaKVXbePumkMePxZaPlZdBhxxrXzW7rzEQy1Vmb/9SmUWQvfP+VmuSov2AWM4bQmKNs+RWMaq6a9j/AweIlFxAxws/xWZr5aHVNPC74LlrN6gNiK00Guh1+jOTvomnLWTQL87U9PAsFaQ/fQccYPA6MB/kSbR3HnbkfdUDaH2eJ0/3pe7Ss5I5D8JU=,iv:yhqZpTzsBLSVQm6PktQxCMPlad/SIYw5zjBJ5Bvas44=,tag:6BfXXeR+iA4jC4wR3//amA==,type:str]
vps_admin_pubkeys:
    - ENC[AES256_GCM,data:KSWtUoUdaBh7RO6SZtXdD0+PePIApQ1ByDrOPsCAjn7HcvKaoSxq9/j3dlPN6Lht9+eweJGBnskN7b7TeuS+dlZfAzQQT8QjxiWwB9KA+Z4cwpvcn19W6ynT6IPVAKLcVTtjf9M3nLRDcT2LoEldUfBkI9DktqxiQGtRwCHuX3UilEGrTpKdqDaUbbn4,iv:4v2d9+tInZ1OxouSCnR4dGw2aojrY1hTREt+FrVHdkE=,tag:upyEUShrEjfGggFwx1SCVA==,type:str]
    - ENC[AES256_GCM,data:h85+cepnhLASX6EVeRoi83kL1ScQQcyWaJttA78PAXhUMxOM6Fnud9Fgx/mI2KsK+7SEQrSHbK4nMlJgyzJekNHIK3TIt3yiEzs1ivsDp8zPrpjzxRFp5YI7rFmxaLo7MIChYqcz8DgGTpUrGMNs+oPV0qrmXpvQG+R8qZLjkG5OWUIz4Q1HP3VeVXTEKptzqYgJUrk=,iv:w/8cH6qkhOe30zWjLUt1YPD53+Zb0BMMFrs2CV5AhxE=,tag:X38lmme1CdJLFXQh2gMvmg==,type:str]
#ENC[AES256_GCM,data:u6aVc45pvgpeCqx4cYHiubaBl081b6pv9RzHYaGlPmjCcGI59vDs5OOfRbPnyIyvozRXgZD5djLg+niVGIOhIUo=,iv:oI/eTS3oKph9Ksy/6ZFyLlzJ9KajjoTCdRhUAaOb+TY=,tag:5SAsAxrNsdmpgidbmJO3wQ==,type:comment]
cloudflare_ssh_hostname: ENC[AES256_GCM,data:bKhoIyV20gKTU+s0NA60lHbWZg==,iv:12bTQJR7BbCNeICQyyx6rpm6ugsOKTXCrYgyPotAAuk=,tag:CW0xCwaNF6vd8nBPq6nVGw==,type:str]
#ENC[AES256_GCM,data:Cdfxx8EcvdlsU75sE+Yimg2scsZ7i3eU/X+RTNSGqLcE196qHTmaQSAT6Bo5F4LlhudF2wcoUwqggA==,iv:ian4lyKlJH/Lhvp2UzHEZ3gJqjXXZpH54rWHYM1TPqs=,tag:UJKGkfM+p2SsOw659hjcjg==,type:comment]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:cIDsztQKSfoSwLgzDy1p,iv:r9vfctr5DfSuo6TWxn+Ku/S7GP4ijuCHAJG59XWOHXE=,tag:tW6PbeIVVpz1BqPQGyuIBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHhoT2M3USBBN1NnQk1t
            Y2lPSjFDaC8vVVp6emFNcit0elZFTmZ1Q0NibE9YZGNZZzBHSwpnUldNeEQ5VG1y
            cUxoWVFrdDBwYmozSm92ejBzdUF0eG1hcGtacXRUWFN3Ci0tLSBmdVM1Vlp5U3Bv
            c3ZFOVlXeXMwS1hMZWo4czl1TEZnbW1YSDFqRHZOdWNvCjCzSV8fxp4dhKjZ0+qW
            9AOSwzF6rLq2htNNAOqPY0bYJ4ipKzyLk/84kurVODb1AO3Qj7Aw48vu10C4QVuI
            mzM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qww9600wzmnjx3rhy46azr5302jva9ny978jdvcvnz3w3lya8uvcvt6jsxr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFRiNmphUSBBOWlNdUo4
            TE42czNQRDBpMXl3UnF3d01vTEtRdmdVQVFhV1RsUTlacnYvZgpMeVVCdXl3eGcr
            T21kSVY3djFUakNDOFROTHkvckxRbFp5c0l3WGNEZjIwCi0tLSBsUDhnNnpIdTRV
            VVM2NTBLOERyT1duOWE2cGhJWGx6S2o1RE9FdVpsNWpVCnyKanqSroCxW07449ZH
            8Ult2CFEYq//3zGFkiTR24mxcFhU+e09adLxzuU5UYWdK2gOtroGPUCnyN+tGV+3
            S4I=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qt2838llhrp5q7gv8zyh3dtm4a49v77c4jzxnwm64lmssa6ndmkqcf98xwf
    lastmodified: "2026-09-15T18:39:33Z"
    mac: ENC[AES256_GCM,data:WWkQ0oaRB759QasfwhHOWehYJ3vYlBjpvLHbSXTxLqYaVCOpltE48ITSyRg6SJwSP4mmBGLbpK0XqenHW6Qm0Ri5djJyqsMQa0jUeru/oMIwFIx4WXS716/i2vahjWkkNTN97ARwilIDbWFlLNmzoeGiAhNt9Vjvyr5I9oRthXw=,iv:2v4LEWLfluPwROsmJUxSSiKt9PBL4bRLAlm6zK7JLbM=,tag:MmJ5a/KVwzDSLYhBq5zMQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
