#ENC[AES256_GCM,data:QxWla6/E9pE1GpYj96RynLspKsjGkQJiED+H5lZhZnpLQXcnZ7Be7d6UkDKRVx8sVce/74xlXrTSAJKk,iv:EAki0dmjZpkkSYHfQhYQ/qXefaoy98gdWOgFmElhKM0=,tag:JMHPcJCpT1J/eThNYfpEqQ==,type:comment]
#ENC[AES256_GCM,data:EB3aTdJseHhkdohZwAzmdKOx/JKGNHVd66K/VMhuexHHyZw6Sl49hQ==,iv:mYLyQDOEkXaGpBhCmq+eD/Z0PAQOwPxeZ//IZ1/OJ+Q=,tag:yR7iPljuILYIIOKAk7u37w==,type:comment]
#ENC[AES256_GCM,data:j99RwuIZc2ANTMkJP6aXxUlRSVc/Zl1rvQDi8awcMVsjUN1IfLuyAWN5/nI9PAY4vGjNNrDozQb+o0X4z9XpW/M=,iv:yeNVvAykOaQZG/VLpagyG4Mb3Xf6YbDm2J+KQN2L/lg=,tag:3G6cEomrHM1C5oDDLMEqbQ==,type:comment]
vps_user: ENC[AES256_GCM,data:THZsM5ZXfOQ=,iv:RPoHRPo2D8V3SdF5mRfqX/gRS+H3KtNRQzN8gBWwmgg=,tag:PVJI0kT0p9FRP6TFMys1Tw==,type:str]
#ENC[AES256_GCM,data:XmK7D2wcB1PJYrFwsl3tvzHLF44bq/fe49lkI7+Ucgvc5evfrfsmRodN4Ko8hcguEZh7HqzDMRY96kw=,iv:24bZ5MvuKYfYAokyORYq8d5taPtAkLsapPJLzALksqc=,tag:XYhd46/z1p5jwmYSQxUMjw==,type:comment]
vps_user_pubkeys:
    - ENC[AES256_GCM,data:Ld389wQTsZ89gN3sIDH4xU0Ozv8r3kyqvcbKWtgdsZM/vZKLjIJcP9rGeuE3B4J3OLRl7FlHyB2eZqTbd6wU5H1EFPUsdj0xy0TKzVQrgnEN1kGZ0t8Seg==,iv:X4tWrJ0274ysUoyKb45+RCB9W2qZu2KVAXtGFyTHPL8=,tag:JKqG1TXJUyVnlqZtfkDy3A==,type:str]
vps_admin_pubkeys:
    - ENC[AES256_GCM,data:j5iKUUlvaMC/auBVNc2g14WeHzHDL5CNqC5IuJqoqSI+Cy0qlbM5zqIf6oA2XAghIRM/TvVmWhs478dNoxG2OBnSGZLuZFND+yk13PBGFxtD1wcxm46LaA==,iv:+bVCWWU5ZVwNU2ddq6laeo4VDttV5pOJ/FljwfIOiws=,tag:p/rXfVvY124suhb/ow/8ow==,type:str]
#ENC[AES256_GCM,data:LZUFHjyqgrhw2i3GIBMgG64OuhRJGngICwBIWVF7kw1hxyb8NCmZzTUm2jFma0s28+OjR37Rw5QOUi7/f6gwggc=,iv:oI/eTS3oKph9Ksy/6ZFyLlzJ9KajjoTCdRhUAaOb+TY=,tag:xvHNDVQ4hEajpDJQTzSSlA==,type:comment]
cloudflare_ssh_hostname: ENC[AES256_GCM,data:+9R5Q06wyCufXKS8NGRdcVm2Qw==,iv:12bTQJR7BbCNeICQyyx6rpm6ugsOKTXCrYgyPotAAuk=,tag:1BbHw3PJZL/esAk0bt4AVw==,type:str]
#ENC[AES256_GCM,data:Mfi/nw31Nfo5IynOFcYEeTu1oLD/sgThqT8sOnSg/N6ENrAv6Wp/sP2YyNcHD7CHykfOXCLZ8CitRQ==,iv:ian4lyKlJH/Lhvp2UzHEZ3gJqjXXZpH54rWHYM1TPqs=,tag:pzDdv7bx99YxivHIwYgdPg==,type:comment]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:67FWmIyII4uYJn7umg==,iv:7n9aqdzbh3m1EufqCIWsB8fUitkTHnbfRqaR7XWcZBM=,tag:jKHRKrJJpyIM6TdpT8o/3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFRiNmphUSBBa1FqNE50
            a0ZkTFMrQlg2OHdBRmdnaDhzZ0RxS05aRUFKRWtRaFAyWE1zVAowb3hiOXd2RDBh
            dW5LalY1aEt4T1VmUW5KeHFqcFNYbXM3R0F6bHJwMGo0Ci0tLSBTUTV0VlFSMTUy
            MEI4WlQ1OXZrOGpiMjVNa291dHo2NDhpQWZENENnUDljCqZB/1UDyKAZdlgg7J8f
            B3YOyLu3if9m9Ng5t4c7zVgJuzMuc3+VS6PRCcnMK8XOt3GZ57rwb00B7lPaU3n0
            76c=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qt2838llhrp5q7gv8zyh3dtm4a49v77c4jzxnwm64lmssa6ndmkqcf98xwf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHhoT2M3USBBa0JscS9S
            bVdFZXJmQURwdnFOcUFwOVorNnhycDJIYW54ZFp3d2tQcWlsSQpRbmNrdnFFZ3Ry
            eENtN2hUelEvczlzeXZOc1hzcmJCWEVVdDRwcjRENmtzCi0tLSBmb0dwOGlXUnBo
            S3ZCd2xJTEpDTDV6OGl1WS96WUxDalpwT2s1SUo2bGEwCpHK8mHfXD5qTIAFyBE/
            /AoX4zKOaN0bI+zjxg+1coETGk3L6WEI0XwRpf6ByZOQsl0BVzq7Ek84b5LMZbqu
            TI8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qww9600wzmnjx3rhy46azr5302jva9ny978jdvcvnz3w3lya8uvcvt6jsxr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSUV0M3U4eUk1bnZvMEt5
            QmdUblMxcmZDT1JrZm02QXhCajVURUhoVkVvClBYNVlpYVdlK0lQcS9sTk9LNlcz
            N0E5blhNODBMV0FvNlBTNElESExBTEEKLS0tIDJwa0FuTHhieHdoclJOWkRjRjU4
            MTBHYkRhWEFMNFNnK3ZBMlVNeVdoekUKBFIxGDQb/Au+Zl3Lma7LmNBy87QpCrAv
            c/CTEF8ZNy+wShd8cfCzSKvM/jpUPqokDha2BEG/tzeF9MuDSCA6YA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157xv0anmkpk2yqh9jnm6tpcgcse2z3z0hgmrlc3jjc4edgsju4fqgeh23h
    lastmodified: "2026-08-04T13:40:48Z"
    mac: ENC[AES256_GCM,data:qypfR/ZhZ8Wdi36fyQFLjT8ojKU8TD9tNxAgoO3flbd4Y4yryyxhioNXPneM/fUKMnNllUmYHgJPVef/2zUbdyPC5lyfcMQOD/anMnn260IMZ0ZcUGtWioJ/JRNHB5M9hc8SbNRQ98/sFKgeEFlu6F1nl9Ogqe/Lm82xFd8ztDQ=,iv:099drjnpUlSGtL7AhElGe8V1t37rczD13YT81aEFcj8=,tag:JyGutZ0EuZOcVS6FjXpwHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
